/**
 * Automation API provider
 * Automation provides template of this description, and anyone may modify it in your own project.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrganizationOut { 
    child?: Array<OrganizationOut>;
    code?: string;
    comment?: string;
    creationTime?: Date;
    creatorName?: string;
    creatorUserId?: string;
    deleted?: boolean;
    deleterName?: string;
    deleterUserId?: string;
    deletionTime?: Date;
    hierarchyIcon?: string;
    hierarchyId?: number;
    hierarchyLevel?: number;
    hierarchyName?: string;
    id?: number;
    lastModificationTime?: Date;
    lastModifierUserId?: string;
    likeCode?: string;
    lineno?: number;
    name?: string;
    parentId?: number;
    parentName?: string;
    tenantId?: string;
    tenantName?: string;
}
