/**
 * Automation API provider
 * Automation provides template of this description, and anyone may modify it in your own project.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BusinessPropertyDTO } from './businessPropertyDTO';
import { ComponentDTO } from './componentDTO';
import { TemplateDTO } from './templateDTO';


export interface TemplateElementDTO { 
    businessProperty?: BusinessPropertyDTO;
    businessPropertyId?: string;
    component?: ComponentDTO;
    componentId?: string;
    componentParam?: string;
    id?: string;
    index?: number;
    template?: TemplateDTO;
    templateId?: string;
    width?: number;
}
